# Generated by Django 2.0.5 on 2018-05-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='film',
            name='film_type',
        ),
        migrations.RemoveField(
            model_name='film',
            name='production',
        ),
        migrations.AddField(
            model_name='film',
            name='film_types',
            field=models.CharField(default='', max_length=100, verbose_name='Film Type(s)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
