# Generated by Django 2.0.5 on 2018-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20180508_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.IntegerField(verbose_name='Menu Order'),
        ),
    ]
